package git

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// FS builds an in-memory file tree for use with Repo.CommitFS.
type FS struct {
	entries  map[string]string
	links    map[string]string // rel path -> symlink target
	toRemove []string
}

// NewFS creates an empty FS builder.
func NewFS() *FS {
	return &FS{entries: make(map[string]string)}
}

// File adds an arbitrary file. Chainable.
func (f *FS) File(path, content string) *FS {
	f.entries[path] = content
	return f
}

// Symlink adds a symbolic link. Chainable.
func (f *FS) Symlink(path, target string) *FS {
	if f.links == nil {
		f.links = make(map[string]string)
	}
	f.links[path] = target
	return f
}

// Add adds all files generated by a Chart builder (Chart.yaml and optionally
// values.yaml) at the given path. Chainable.
func (f *FS) Add(path string, chart *Chart) *FS {
	f.entries[filepath.Join(path, "Chart.yaml")] = chart.marshalChartYAML()
	if chart.values != nil {
		f.entries[filepath.Join(path, "values.yaml")] = *chart.values
	}
	return f
}

// AddDir copies all files and symlinks from sourceAbsDir into targetRelPath.
// Chart.yaml is taken from the chart builder (with version already rewritten).
// Symlinks are recreated with the same target. All other files are copied
// byte-for-byte from disk.
func (f *FS) AddDir(targetRelPath, sourceAbsDir string, chart *Chart) error {
	f.entries[filepath.ToSlash(filepath.Join(targetRelPath, "Chart.yaml"))] = chart.renderChartYAML()

	return filepath.WalkDir(sourceAbsDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(sourceAbsDir, path)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if rel == "Chart.yaml" {
			return nil
		}
		targetKey := filepath.ToSlash(filepath.Join(targetRelPath, rel))
		if d.Type()&fs.ModeSymlink != 0 {
			linkTarget, linkErr := os.Readlink(path)
			if linkErr != nil {
				return fmt.Errorf("readlink %s: %w", rel, linkErr)
			}
			f.Symlink(targetKey, linkTarget)
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("read %s: %w", rel, readErr)
		}
		f.entries[targetKey] = string(data)
		return nil
	})
}

// Remove marks files for deletion in the next CommitFS call. Chainable.
func (f *FS) Remove(paths ...string) *FS {
	f.toRemove = append(f.toRemove, paths...)
	return f
}

func (f *FS) files() map[string]string {
	return f.entries
}

func (f *FS) symlinks() map[string]string {
	return f.links
}

func (f *FS) removals() []string {
	return f.toRemove
}
