age_keys:
    release:
        github_secret_name: ENC[AES256_GCM,data:Y5cK9+UUxfZVYUPmnRd1sbORMVA=,iv:FYUOM1TxagAULRXfI4dRAXZ8LcofqaVV7B69X2Zg+78=,tag:+7+GeKoYjl1y0tK8D/8QwA==,type:str]
        private_key: ENC[AES256_GCM,data:8kR6G00g8TUUXh9MGg1o8NSWjlMJfX5oF8PdKJBDuAM10/HvB3je7RrJpn8+JGuyNBRgto08GEqGKUAv40GaG2ZGcwNCOLcvAfNJd0zlAiQWc6/8pV1rLZCsdLjzADqfmOBelVK/DAJbt+SSvq1StCCSvX95VuzLPtvSMgVfsl1Lb/mB96oBAEol02w0hI/+dYNIUDZX+s6xFgIz8NudJHwt88hzQRyMqsP5ioXSdVcry4JZ3CDYTKAuuhA=,iv:ovnPaFcSSFb36NXOCYm07917RcKe/IiRyYnHFVBplz8=,tag:m8Nijb3/RZTLOIuxoZn+Fw==,type:str]
    publish:
        github_secret_name: ENC[AES256_GCM,data:h8wq1wVTilMgqEgcSqdtTI9ekWA=,iv:wkV0g8adaE6m+d511tc3yyaKzfMj5uubzhmK7mTiGoE=,tag:6u/r+V+TEnSP4agDOair1w==,type:str]
        private_key: ENC[AES256_GCM,data:wusYrGvLEK3ZWjXH7u0gkyumqlgtqxS/HwiY7yWARLjCwDNHHQZkumhXSOj2PS3isxNVT34NMCjOBUkP/ePNg2BVANB1w0uQyVvMWnK62J7iyRXBk0o1MPVukgURcaFHRpFgayZkZEIccSFk6wAf3HtV4NLVkhoPnpCyI1Eq+Au6k+8/zymrOeA+SFrwdsIsvfAmvK2E6T2PUIIx699sN/iiosUSkAgjSTmSdliw3M7c2JIvSbXqbmgv51s=,iv:ppOrakmGhFTOiBkqCYuYwEtPTho/9E4yM3m886/hqVg=,tag:CM7rwDKa1w1WCXQPSSbf8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USBtQlZZ
            ck9BM09jOGI3aGM5M3lacDlUZVdud2diUmJjamE0RklhTSszSzEwCjZhOXlJMFZt
            aGlNRncyY1QyNU5nKzNIVnpRRmxFd29PY2RsbHVoL09PZ1kKLS0tIFNrYW85Ukl4
            VldJR1Nxd1R5MkU4UlBMdloxazVHMm5wTTZoK1ZzSWpYd3MKwWyW8jvyJgLJpAh8
            pM0HM5WZSsXYD/U8uUFgkDcG3+fFoetRyM0wySKl2X0G/gIQEXQCszE3h0+UI+BW
            VU2hSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
    lastmodified: "2026-06-03T15:05:57Z"
    mac: ENC[AES256_GCM,data:noZ0ySdqTpYrZga2hvEiX+5WPKp0pVfzjVQh2sAYOwy2QcVvTrDsr3k+1V24fhULsd3NrHaUiXbuAOnHy/jVnoVErnGbdLVuIteM14w/iijL/9T5WPKOBAd8UxmFC2diTheGc5ni01n2cI3C7AKVO/2/30g7QVYoeJkmXXYBSUU=,iv:aS7vbVyGW2r98uP+2drZOruY3SvkD4GC2Ob2V7vEo0k=,tag:LH5v3CiUnU+jVMRIUBYjGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
