owner_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>"

semantic_release_age:
  public_key: age1vmc2s5w8rfadyvn779mj8lawq8nh97fs4a2tft748xecc8lmgynstj8jus
  github_secret_name: SOPS_AGE_KEY_RELEASE

publish_age:
  public_key: age1c5kdlgv43ehhngrnukjfc639hk00qa826tzk29k9j97tp9xtwefq3x4ksw
  github_secret_name: SOPS_AGE_KEY_PUBLISH

git_signing:
  public_key_openssh: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhXgMT+W7/+23kXnqtXmQNRFHAL75b+3bcBn7bX+wLL release@hydra-gitops.org"
  github_secret_name: SEMANTIC_RELEASE_GIT_SIGNING_KEY

cosign:
  public_key_pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEw1aXBxi1YwXL5O8Mt+idR7Wi3S6+
    E708OzHNU25L4aSRd4mjsOxw4ASO9qxp8j6PhON6sbwlII24hkw3c7LKrg==
    -----END PUBLIC KEY-----

homebrew_tap:
  public_key_openssh: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJOatDq8GkEnmuCZ4R527ZoR1oiog+Wy9W9stGMo6a+2 hydra publish homebrew tap"
  github_secret_name: HOMEBREW_TAP_DEPLOY_KEY
