git_signing:
    format: ENC[AES256_GCM,data:j/mFJm1DH7NE5Fg=,iv:JTaEIZBQbUwiuKd7b8PERTB6mQc4KVax0UCQ7RylSAg=,tag:wEiQETO8KJKXHwARAo0H0Q==,type:str]
    private_key: ENC[AES256_GCM,data:5b5lmdYytoIoRF1Sl0mOqAZTCIyhZ4tA17Qsi4Mx8V/b+V37Q8IPrvltwu0wsPvuDL62pYDRooY0hhgrkJRnRQM3De4iEMZFKKNa7LxgyeOG19oxUsqWp+M/DIkQf6JT8T5AI/CqLR7fS5yr64nIAddM2/8OxtVf+vgk0X7ajZD+YI1Pe4N5FrnDxM3UyYt2FegSutJKtSsvdrCcJPaK2vpqDiHjcqalD/nj/o7gyeKdh7iC3XsQ4JuyOcVzb6tp79MvAO6tiLQK+Ffv8zVt2oi4FaRHsIiOn24DbW5FFO+WJqu1JsXHVG0My2nU3BVeWwdV6h2zUIu+/lBmt5iG+vqqbMhtgw+eLlm+ietu1RhGD/6Wv58P5hMGx6NKl3JdCm49MZ/2uislqPrOA6pec6LN7F6riTbNyV8S+pZrvrY1pKZWiUqU9B1U4X2CvxEBYZlD9SF+fQ5tANYgWitrD4UHGpj1R6u0vgx0Iyk3tB3Mjy3240pfg0U7oFIMScbjBctBdCqy25kR5mvkuFtAv4ty/Z36TTEr9Shj1flH8cUIfEefO/jZmJj3Ae8LyDY=,iv:gzAzlS27Wg+lFaNy6Ei6/72a/NbIC3D/hfoxwEfzR3c=,tag:UFu4YWfMOpOVy3VLi1qujg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGxlZVo3USAyeHZq
            Wk5WMEV4ckZZWGoySHFSOTd4YXpWOGxzWHMyU2NMUERnVHFGN1hRCkJDZ2FZM1Nl
            dWJnSDhlZjFvaVBvekkyeTdjdHlTUzFJOWhmRkFnbytJdk0KLS0tIG1IVHMwYm9H
            QURGVUZrb3hZZkZFVUEzVTgxT01OdmdLaS84MnIyQnFQMWMK9l5M0uNYI16C0dXn
            ndyCuHYuc+T8CemSiX8swtKXcNdE280rdkkH3bPGtsJW5zkeLixHlQuDA+UaD6Nh
            exUr8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrL1CJG09aLg6F4A2+TXINIKZRVHr8KUVoHDy0FWXB Dennis Rieks <dennis.rieks@rohde-schwarz.com>
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZS9ucSt3SUZKK3VyYW1L
            Q1pEYnJ6TW5yOFVyZWRVR2dWTHh1ZkZycFVvCktUQzlxWjhESnVHYlNJZkp4UWZR
            c3FNT1pNdTdLUThGd3ZiSWpYSVdyYkkKLS0tIGtiWmZJbDlrWm5JN0wySjg4SEh4
            ZTFaWmFNMHlkaTJ5MzZmYzRYRlIzRWsKLP8wWLO+yHGYW2Z37sAWvQ/Tj+QTFjUY
            zhmQtYpMt2mmVZMrWuMC321aV3PITvZx811iwYnWiMfjhQkQVbSZBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmc2s5w8rfadyvn779mj8lawq8nh97fs4a2tft748xecc8lmgynstj8jus
    lastmodified: "2026-05-28T14:06:08Z"
    mac: ENC[AES256_GCM,data:wAygIkzP+6DDy7CpFd9F1ZtwtnJf6UbWWeL3xhoHA8/8ZfMRYQyv7EitBq9xfhc74+3YLTJa0fKHHKQUpZuB3GD1+XCDp2gb5O51JkmBvN2VphdZlSuwKcZF2AFmfMxdk33H/X+U08rAFYadu6VJutoxXN3U2M6jbVODWCoGxdk=,iv:/85gBywcGaioTZdJ0wbxpDwg76mQM02sZDh1K0vNy24=,tag:Fexa7SQE0/rXLXtstUO7tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
